Lesson10 try1
IgushkinV/epam-java-course pull request #14
Opened 2021-04-27 17:30 UTC by IgushkinV

Task without stars.

2021-04-27 18:15 UTC, tlt-java-courses requested changes

2021-04-27 18:15 UTC, tlt-java-courses commented on pom.xml
> +
Пора в мастер внести эти изменения? )

2021-04-27 18:15 UTC, tlt-java-courses commented on src/main/java/igushkin/homeworks/lesson10/taskone/TaskOne.java
> +                );
Лишний перенос перед );

2021-04-27 18:15 UTC, tlt-java-courses commented on src/main/java/igushkin/homeworks/lesson10/taskone/TaskOne.java
> +            }
try без catch не есть хорошая практика

2021-04-27 18:15 UTC, tlt-java-courses commented on src/main/java/igushkin/homeworks/lesson10/taskone/TaskOne.java
> +        //Оставил строку, чтобы продемонстрировать выполнение задания.
Подстраивать код под тесты не правильно. Расскомментируй и подгоняй тесты уже

2021-04-27 18:15 UTC, tlt-java-courses commented on src/main/java/igushkin/homeworks/lesson10/taskone/TaskOne.java
> +     * Writes UUID from the passed list to the file
Точки в конце JavaDoc и переносы строк перед перечислением параметров

2021-04-27 19:32 UTC, IgushkinV commented on src/main/java/igushkin/homeworks/lesson10/taskone/TaskOne.java
> +                );
Исправил.

2021-04-27 19:32 UTC, IgushkinV commented on src/main/java/igushkin/homeworks/lesson10/taskone/TaskOne.java
> +            }
Да, исправил. Добавил catch.

2021-04-27 19:33 UTC, IgushkinV commented on src/main/java/igushkin/homeworks/lesson10/taskone/TaskOne.java
> +        //Оставил строку, чтобы продемонстрировать выполнение задания.
Переделал, исправил.

2021-04-27 19:33 UTC, IgushkinV commented on src/main/java/igushkin/homeworks/lesson10/taskone/TaskOne.java
> +     * Writes UUID from the passed list to the file
Исправил.

2021-04-29 17:23 UTC, tlt-java-courses approved these changes

2021-04-29 17:23 UTC, merged