One star task solution.
IgushkinV/epam-java-course pull request #17
Opened 2021-05-01 11:45 UTC by IgushkinV

2021-05-01 18:17 UTC, tlt-java-courses requested changes
Для чего пустой файл  `src/main/resources/null.txt`?

2021-05-01 18:17 UTC, tlt-java-courses commented on src/main/java/igushkin/homeworks/lesson10/task2/TaskUtilities.java
> +        try (FileWriter writer = new FileWriter(path.toFile())) {
Давай использовать функционал Java 8/11 для считывания из файла

2021-05-01 18:17 UTC, tlt-java-courses commented on src/main/resources/sausage.txt
> +rO0ABXNyAClpZ3VzaGtpbi5ob21ld29ya3MubGVzc29uMTAudGFzazIuU2F1c2FnZbOyBNZ53T3mAgADSgAEY29zdEkABndlaWdodEwABHR5cGV0ABJMamF2YS9sYW5nL1N0cmluZzt4cAAAAAAAAAAAAAAAAHA=
А что это за файл?

2021-05-01 18:18 UTC, tlt-java-courses requested changes

2021-05-01 18:18 UTC, tlt-java-courses commented on src/test/java/igushkin/homeworks/lesson10/task2/TaskUtilitiesTest.java
> +    public static void prepare() {
setUp метод обычно называют

2021-05-01 18:18 UTC, tlt-java-courses commented on src/test/java/igushkin/homeworks/lesson10/task2/TaskUtilitiesTest.java
> +    private static List<Sausage> sausageList = new ArrayList<>();
static переменные в тестах не используют

2021-05-01 18:30 UTC, IgushkinV commented on src/main/resources/sausage.txt
> +rO0ABXNyAClpZ3VzaGtpbi5ob21ld29ya3MubGVzc29uMTAudGFzazIuU2F1c2FnZbOyBNZ53T3mAgADSgAEY29zdEkABndlaWdodEwABHR5cGV0ABJMamF2YS9sYW5nL1N0cmluZzt4cAAAAAAAAAAAAAAAAHA=
Это файл, в который записываются закодированные объекты. И потом считываются из него.
Его не должно быть?

2021-05-01 18:40 UTC, tlt-java-courses requested changes

2021-05-01 18:40 UTC, tlt-java-courses commented on src/main/java/igushkin/homeworks/lesson10/task2/TaskUtilities.java
> +        return Files.lines(path)
А что так сложно всё это?

2021-05-01 20:30 UTC, IgushkinV commented on src/main/java/igushkin/homeworks/lesson10/task2/TaskUtilities.java
> +        try (FileWriter writer = new FileWriter(path.toFile())) {
Использовал Files.lines.

2021-05-01 20:31 UTC, IgushkinV commented on src/test/java/igushkin/homeworks/lesson10/task2/TaskUtilitiesTest.java
> +    public static void prepare() {
Переименовал.

2021-05-01 20:31 UTC, IgushkinV commented on src/test/java/igushkin/homeworks/lesson10/task2/TaskUtilitiesTest.java
> +    private static List<Sausage> sausageList = new ArrayList<>();
Убрал.

2021-05-01 20:33 UTC, IgushkinV commented on src/main/java/igushkin/homeworks/lesson10/task2/TaskUtilities.java
> +        return Files.lines(path)
Упростил, убрав промежуточный этап с байтами. Больше упрощений пока не вижу.

2021-05-02 20:17 UTC, tlt-java-courses approved these changes

2021-05-02 20:17 UTC, tlt-java-courses commented on src/main/resources/sausage.txt
> +rO0ABXNyAClpZ3VzaGtpbi5ob21ld29ya3MubGVzc29uMTAudGFzazIuU2F1c2FnZbOyBNZ53T3mAgADSgAEY29zdEkABndlaWdodEwABHR5cGV0ABJMamF2YS9sYW5nL1N0cmluZzt4cAAAAAAAAAAAAAAAAHA=
По заданию записываться во втором задании ничего не должно, был приложен файл к ДЗ

2021-05-02 20:17 UTC, merged