Homework 14.
IgushkinV/epam-java-course pull request #21
Opened 2021-05-22 05:35 UTC by IgushkinV

Task1

2021-05-22 13:51 UTC, tlt-java-courses requested changes

2021-05-22 13:51 UTC, tlt-java-courses commented on homework-db/pom.xml
> +        </liquibase-maven-plugin.changeLogFile>
Для чего перенос?

2021-05-22 13:51 UTC, tlt-java-courses commented on homework-db/pom.xml
> +
Для чего перенос?

2021-05-22 13:51 UTC, tlt-java-courses commented on homework-db/pom.xml
> +    <properties>
Проперти обычно идут перед депендами

2021-05-22 13:51 UTC, tlt-java-courses commented on homework-db/src/main/resources/db/changelog/db.changelog-master.xml
> +    <include  file="src/main/resources/db/changelog/db.changelog-customer-1.0.xml"/>
Зачем нам так много ченжлогов? Давай объединим их в один сложив в подкаталог и назавем как-нибудь понятно включая и версию.

2021-05-22 13:51 UTC, tlt-java-courses commented on homework-db/src/main/resources/db/changelog/db.changelog-master.xml
> +<databaseChangeLog
обычно кумулятивный ченжлог называют database_{название проекта}_changelog.xml

2021-05-22 13:51 UTC, tlt-java-courses commented on homework-db/src/main/resources/db/changelog/db.changelog-customer-1.0.xml
> +
Для чего эти переносы между тегами?

2021-05-22 13:51 UTC, tlt-java-courses commented on homework-db/src/main/resources/db/changelog/db.changelog-customer-1.0.xml
> +    <changeSet id="2021-05-20-creating-customer" author="Vladimir Igushkin" >
Vladimir_Igushkin

2021-05-22 13:53 UTC, tlt-java-courses requested changes

2021-05-22 13:53 UTC, tlt-java-courses commented on homework-db/src/main/resources/db/changelog/db.changelog-order-product-1.0.xml
> +                <constraints primaryKey="true" nullable="false"
Для чего тебе первичными ключами здесь делать записи? Учитывая что они при этом ещё и вторичными являются

2021-05-22 13:56 UTC, IgushkinV commented on homework-db/pom.xml
> +        </liquibase-maven-plugin.changeLogFile>
Не умещалось в одну строку. После Ctlr+Alt+L так перенеслось.

2021-05-22 14:01 UTC, IgushkinV commented on homework-db/src/main/resources/db/changelog/db.changelog-customer-1.0.xml
> +
Я думал, что как между <dependency>, чтобы читалось легче.

2021-05-22 17:10 UTC, IgushkinV commented on homework-db/pom.xml
> +    <properties>
Да, нагенерировал с помощью хоткея и забыл про них. Исправляю.

2021-05-23 00:54 UTC, tlt-java-courses requested changes

2021-05-23 00:54 UTC, tlt-java-courses commented on homework-impl/src/main/java/com/epam/igushkin/homework/domain/entity/Customer.java
> +    @Column(name = "customer_id")
hibernate по умолчанию приводит lowerCamelCase к lower_snake_case, поэтому подобные уточнения излишние

2021-05-23 00:54 UTC, tlt-java-courses commented on homework-impl/src/main/java/com/epam/igushkin/homework/domain/entity/Customer.java
> +@Table
С какой целью аннотация?

2021-05-23 16:19 UTC, IgushkinV commented on homework-impl/src/main/java/com/epam/igushkin/homework/domain/entity/Customer.java
> +    @Column(name = "customer_id")
Сначала везде убрал. Потом пришлось добавлять обратно, иначе возникали ошибки во время исполнения.

2021-05-23 16:19 UTC, IgushkinV commented on homework-db/src/main/resources/db/changelog/db.changelog-customer-1.0.xml
> +    <changeSet id="2021-05-20-creating-customer" author="Vladimir Igushkin" >
Исправил.

2021-05-23 16:19 UTC, IgushkinV commented on homework-db/src/main/resources/db/changelog/db.changelog-master.xml
> +<databaseChangeLog
Исправил.

2021-05-23 16:20 UTC, IgushkinV commented on homework-db/src/main/resources/db/changelog/db.changelog-master.xml
> +    <include  file="src/main/resources/db/changelog/db.changelog-customer-1.0.xml"/>
Сделал. И добавил init.sql.

2021-05-23 20:08 UTC, tlt-java-courses approved these changes

2021-05-23 20:15 UTC, merged